# Make-A-Video: Text-to-Video Generation without Text-Video Data
#
# Configuration file for implementation of "Make-A-Video: Text-to-Video Generation without Text-Video Data",
# (https://arxiv.org/abs/2209.14792).
#
# Make-A-Video improves over "Video Diffusion Models" (https://arxiv.org/abs/2204.03458)
# through several architectural improvements, designed to retain the image generation
# qualities of a pretrained text-to-image diffusion model while learning the temporal
# dependencies from unlabeled videos.
#
# - Fine tune an existing T2I diffusion model for video generation, using
#   factorized spatiotemporal convolutional layers and attention
# - Frame interpolation model for generating higher frame rate data
# - Video super-resolution networks for generating high resolution video data.
#
# The original paper operated in the latent space (using text embeddings to generate image embeddings),
# and a decoder network to generate low resolution images from the prior-generated image embeddings.
# here, we will generate low-resolution images in pixel space (at 32x32) and use the super-resolution
# models to upsample to 64x64.
#
# Pseudo-3D Convolutional Layers
# To factorize the space and time convolutional layers, the authors introduce a Pseudo-3D
# convolutional layer which first performs a 2D convolution over (B F) C H W, followed by
# a 1D convolution over the temporal dimension (B H W) C F. The 2D convolution is initialized using
# the weights of the pretrained T2I model, and the temporal attention layer is initialized to
# the identity function.
#
# Pseudo-3D Attention Layers
# Similar to the Pseudo-3D convolutional layer, the 3D attention layer is simlarly decomposed
# a pretrained 2D attention layer, followed by a 1D attention layer over the temporal dimension
# that is initialized to the identity function.
diffusion:
  parameterization: "v"
  # Sampling section determines the size of the sampled output
  # from the model, and defines the sampling method used
  sampling:
    output_channels: 1
    output_spatial_size: 32
    output_frames: 16
    target: video_diffusion.samplers.ancestral.AncestralSampler
    params: {}
  # The noise scheduler to use with the forward diffusion process.
  noise_scheduler:
    target: video_diffusion.scheduler.ContinuousNoiseScheduler
    params:
      num_scales: 1024
      logsnr_schedule: "cosine"
      loss_type: "l2"
      logsnr_min: -20
      logsnr_max: 20
  importance_sampler:
    target: video_diffusion.importance_sampling.UniformSampler
    params:
      num_timesteps: 1024
  # A preprocessor to use with the context before sending to the score network.
  context_preprocessing:
      # The Prompts Preprocessor converts the list of text prompts in the context
      # into a batch of text tokens of shape (B, text_context_size)
      - target: video_diffusion.context.T5TextPromptsPreprocessor
        params:
          # The max length of the text token sequence
          max_length: 77
          # The name of the T5 text model to use
          model_name: "google/t5-v1_1-base"
  # A preprocessor for input to the model.
  input_preprocessing:
    target: video_diffusion.context.IgnoreInputPreprocessor
    params: {}
  # Setting for classifier free guidance.
  classifier_free_guidance:
    # Classifier-free guidance scale, where the value is >= 1.0
    classifier_free_guidance: 1.0
    # Unconditional guidance probability
    unconditional_guidance_probability: 0.2
    # The context signals to apply guidance to.
    signals: ["text_prompts"]
    # For classifier free guidance, we need the ability to create an unconditional
    # context given the conditional context. This unconditional context needs
    # to be applied in both training and sampling, and will return a new
    # context dictionary given the original context dictionary.
    unconditional_context:
      target: video_diffusion.context.UnconditionalTextPromptsAdapter
      params: {}
  # Defines the score network for predicting the noise parameter
  score_network:
    target: video_diffusion.score_networks.unet_pseudo3d.Unet
    params:
      # The number of input channels to the model.
      input_channels: 1
      # The number of output channels to the model.
      output_channels: 1
      # The spatial size of the input to the model.
      input_spatial_size: 32
      # The number of frames in each batch
      input_number_of_frames: 16
      # The number of features/channels at the start of
      # the network. This defines the inner dimensions
      # of the model.
      num_features: 128
      # Resnet block channel multipliers.
      channel_multipliers: [1, 2, 2, 2]
      # Attention resolutions
      attention_resolutions: [16]
      # The number of resnet blocks per resolution.
      num_resnet_blocks: 2
      # Use scale/shift of the GroupNorm in the timestep embedding.
      # This is also called Adaptive Group Normalization.
      use_scale_shift_norm: True
      # Perform resampling using convolutions.
      resamp_with_conv: False
      # BigGAN style resnet block to perform up/down sampling.
      resblock_updown: False
      # The type of resnet block to use
      resnet_block_type: 'biggan'
      # Dropout scale
      dropout: 0.1
      # The number of MLP layers to use on the conditioning signal
      mlp_layers: 2
      # Does the model include a learned sigma or a fixed sigma.
      is_learned_sigma: False
      # True if this is a class conditional model
      is_class_conditional: False
      # The number of classes for a class conditional model.
      # Only used if is_class_conditional=True.
      num_classes: 10
      # Additional conditioning signals for the model. The projections
      # defined here will be applied before running through the rest of the
      # score network.
      conditioning:
        # The signals (keys in the dictionary) that are available in the conditioning
        # context.
        signals: ["timestep", "text_tokens"]
        projections:
          # A projection to apply to the integer timesteps.
          timestep:
            # Defines a projection incorporating the sinusoidal position embedding.
            # Output size is (B, C, num_features * time_embedding_mult)
            target: video_diffusion.layers.embedding.InvCosTimestepEmbeddingProjection
            params:
              num_features: 128
              time_embedding_mult: 4
              max_time: 1.0
              clip_min: -20
              clip_max: 20
          # A projection to apply to the text tokens in the conditioning context.
          text_tokens:
            # Defines an embedding which goes from text tokens at the given
            # vocabulary size to text token embeddings.
            target: image_diffusion.layers.embedding.T5TextTokensToEmbedding
            params:
              model_name: "google/t5-v1_1-base"
        # The context transformer to use at the top of the score network. This transforms
        # the context with a shared set of parameters.
        context_transformer_head:
          # Timestep -> timestep embedding
          - target: video_diffusion.layers.embedding.RunProjection
            params:
              input_context_key: "logsnr_t"
              output_context_key: "timestep_embedding"
              projection_key: "timestep"
          # Projects the text tokens into text embeddings using the projection
          # defined for "text_tokens"
          - target: video_diffusion.layers.embedding.RunProjection
            params:
              input_context_key: "text_tokens"
              output_context_key: "text_embeddings"
              projection_key: "text_tokens"
        # The context transformer to use at each attention layer. This transforms
        # the context with a different set of parameters at each attention layer.
        spatial_and_temporal_context_transformer_layer:
          target: video_diffusion.layers.attention.SpatialAndTemporalCrossAttention
          params:
            # The dimensionality of the context signal coming in.
            # -1 signifies no context coming in, and this defaults to Multi-Head
            # self attention.
            context_dim: 768
            # The number of heads in the attention layer.
            heads: 4
            # The dimensionality of each attention head.
            dim_head: 64
            # Dropout probability to use in training.
            dropout: 0.1
            # True if the input signal will be video, and we need
            # to rearrange in the layer.
            is_video: True
            temporal_sequence_length: 16
            max_relative_position: 16
            # The context adapter for the conditioning signal
            context_adapter:
              target: video_diffusion.context.TextEmbeddingsAdapter
              params:
                # For the cross attention, we want to operate on the embedding dimension,
                # not the token sequence length.
                swap_context_channels: True

# Describes the dataset used in training.
data:
  # Spatial width/height of the data input to the model.
  image_size: 32
  # Number of channels in the input data
  num_channels: 1
  # The number of classes in the dataset
  num_classes: 10
  input_number_of_frames: 16
